name = "readaloud-tts-worker"
main = "index.js"
compatibility_date = "2024-01-01"

# Account details (fill in after creating Cloudflare account)
# account_id = "your_account_id_here"
# workers_dev = true

# Environment variables (use wrangler secret for sensitive data)
# To set the API key, run:
# wrangler secret put GOOGLE_CLOUD_API_KEY

[env.production]
name = "readaloud-tts-worker"
# route = "https://your-custom-domain.com/*"

[env.development]
name = "readaloud-tts-worker-dev"
